server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001

viewRendererConfiguration:
   .ftl:
      strict_syntax: yes
      whitespace_stripping: yes
